"""empty message

Revision ID: 02324a739413
Revises: 5e9a232d8791
Create Date: 2020-10-22 17:37:15.263590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02324a739413'
down_revision = '5e9a232d8791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pocket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('last_change', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pocket_last_change'), 'pocket', ['last_change'], unique=False)
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_type', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pocket', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pocket'], ['pocket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_timestamp'), 'transfer', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_timestamp'), table_name='transfer')
    op.drop_table('transfer')
    op.drop_index(op.f('ix_pocket_last_change'), table_name='pocket')
    op.drop_table('pocket')
    # ### end Alembic commands ###
