"""empty message

Revision ID: 321c804fab65
Revises: 02324a739413
Create Date: 2020-10-25 06:36:21.249875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321c804fab65'
down_revision = '02324a739413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pocket', sa.Column('name', sa.String(length=40), nullable=True))
    op.add_column('transfer', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer', 'category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.drop_column('transfer', 'category')
    op.drop_column('pocket', 'name')
    op.drop_table('category')
    # ### end Alembic commands ###
