"""empty message

Revision ID: 770b600f35fb
Revises: 6bc5996be812
Create Date: 2020-10-22 10:02:58.354511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770b600f35fb'
down_revision = '6bc5996be812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('joined', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'joined')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
